[package]
name = "recastxz"
authors = ["404"]
version = "2.5.0"
edition = "2024"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
panic = "abort"

[dependencies]
libdeflater = "1.25.0"
jni = "0.21.1"

[lib]
crate-type = ["cdylib"]
